# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins:
       - jekyll-paginate
       - jekyll-seo-tag

port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://monirulhossainanik.github.io
baseurl: ""
title: Monirul Hossain
author: Mohammad Monirul Hossain
description: Personal projects and resume
avatar: profile.png
email: monirulhossainanik@gmail.com
github: monirulhossainanik # username
twitter:
linkedin: monirulhossainanik
stackoverflow:    #e.g: users/2735833/proton1h1



# needed for travis-ci build
#exclude: [vendor]
